services:
  django:
    # Сборка образа для сервиса django из текущей директории
    build: ./backend
    # Задание имени контейнера для сервиса django
    container_name: django
    # Задание команды, которую нужно запустить при запуске контейнера для сервиса django
    command: python ./backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    # Открытие порта на хостовой машине и перенаправление на порт в контейнере
    ports:
      - 8000:8000
    # Зависимость от другого сервиса
    depends_on:
      - pgdb

  pgdb:
    # Использование готового образа postgres
    image: postgres
    # Задание переменных окружения для контейнера с postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
     # Задание имени контейнера для сервиса pgdb
    container_name: pgdb
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - vue

  vue:
    build:
      context: ./frontend
    command: npm run build
    container_name: vue
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"  

volumes:
  pgdbdata: null